# -*- coding: utf-8 -*-
"""export.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JfMHGY3nDsprC624U-5SFpf_KF5YowPX
"""

import pandas as pd

# Ruta del archivo CSV ordenado
archivo_csv_ordenado = 'libros_ordenados.csv'

try:
    # Leer el archivo CSV ordenado
    data_ordenada = pd.read_csv(archivo_csv_ordenado)

    # Exportar a Excel
    archivo_excel = 'libros_ordenados.xlsx'
    data_ordenada.to_excel(archivo_excel, index=False)

    print(f"Datos exportados exitosamente a {archivo_excel}")
except Exception as e:
    print(f"Error al exportar los datos: {e}")