# -*- coding: utf-8 -*-
"""read.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GlYWzHai5fUmCgVvATODGPLKjlT6UP62
"""

import pandas as pd
import mysql.connector

# Detalles de la conexión a la base de datos MySQL
config = {
    'user': 'biblio',
    'password': '765',
    'host': 'localhost',
    'database': 'biblioteca'
}
# Nombre de la tabla en la base de datos
nombre_tabla = 'libros'

try:
    # Conectar a la base de datos MySQL
    conn = mysql.connector.connect(**config)

    # Leer la tabla de la base de datos en un DataFrame de pandas
    query = f"SELECT * FROM {nombre_tabla}"
    data = pd.read_sql_query(query, conn)

    # Guardar los datos en un archivo CSV
    archivo_csv = 'libros.csv'
    data.to_csv(archivo_csv, index=False)

    print(f"Datos leídos y guardados en {archivo_csv}")
except Exception as e:
    print(f"Error al leer la base de datos: {e}")
finally:
    # Cerrar la conexión a la base de datos
    if 'conn' in locals():
        conn.close()

