# -*- coding: utf-8 -*-
"""Transform-v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TneemsDupoIVlpFTW1MlBzNOKsyAD7Ve
"""

import pandas as pd

# Ruta del archivo CSV intermedio
archivo_csv = 'libros.csv'

try:
    # Leer el archivo CSV
    data = pd.read_csv(archivo_csv)

    # Ordenar los datos por nombre
    data_ordenada = data.sort_values(by='Anio')

    # Eliminar columnas que no se desean exportar
    columnas_a_eliminar = ['id_publicacion', 'url_repositorio']
    data_ordenada = data_ordenada.drop(columnas_a_eliminar, axis=1)

    # Exportar a Excel
    archivo_excel = 'libros_ordenados.xlsx'
    data_ordenada.to_excel(archivo_excel, index=False)

    print(f"Datos exportados exitosamente a {archivo_excel}")
except Exception as e:
    print(f"Error al transformar los datos: {e}")